export const template = `

  <div class="welcome-background alexa">

    <div class="welcome-hero-cover"></div>

    <div class="welcome-logo">
      <a ui-sref='welcome'><img src='assets/images/yno_tasting_logo_white.svg'></a>
      <desktop-nav-secondary welcome-state="$ctrl.constants.WELCOME_HOW_STATE"></desktop-nav-secondary>
    </div>

<div class="welcome-copy scrollable">
    <h2>Yno's terms of use for Amazon Alexa.</h2>
    <p>Use of Yno Tasting ("Yno") skill on Amazon's Alexa service on any Alexa-enabled device (the "Skill") is governed by these Terms of Use (“Terms”). The Skill allows you to use an Alexa-enabled device, such as an Amazon Echo or Amazon Fire TV, to interact with Yno via voice. If you do not agree to these Terms, do not use the Skill. Use of the Skill constitutes your acknowledgement of and agreement to these Terms, which are a binding legal contract between you and Yno.

You are granted a non-exclusive, personal, revocable, non- transferable license to use the Skill on the device for which it is provided and that you own or control, subject to any terms of service, usage rules, or other terms and conditions provided by Amazon and/or any other the Third Party (as defined below), as applicable. You agree to use the Skill, and all related software provided to you by Yno, solely to access and use the services of Yno and agree not to modify, decompile, reverse engineer, or create derivative works of the Skill. You hereby represent and warrant (1) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country; and (2) you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
      <p>Amazon Alexa and Your Agreements with Amazon. Alexa is a service of Amazon and is operated on Amazon’s systems. Your use of Alexa-enabled devices through which you may use the Skill is subject to your agreements with Amazon and Amazon’s privacy policy. Yno is not affiliated with Amazon and is not a party to or responsible for your agreements with Amazon or for its products and services. The Skill was not created or endorsed by Amazon. The Skill was built for the most current, generally available version of your Alexa enabled device's operation system as of the “Rev” date shown at the bottom of these Terms, and compatibility issues may be encountered when using older or newer versions. Your interactions with Yno through Alexa (which include but are not limited to spoken utterances and the Skill’s responses) could be monitored, recorded, stored, and used by your Alexa-enabled device or by Amazon. Please review your Alexa agreements with Amazon and Amazon’s privacy policy for how Amazon and your Alexa-enabled device treat those interactions.</p>

<p>Using the Skill to Interact with Yno. In addition to these Terms, your use of the Skill is also subject to Yno’s Privacy Notice and to your Yno account agreement if you have a Yno account (although the Skill does not currently allow you to access or transact in your Yno account). Yno treats all communications coming from Alexa through the Skill as originating from you or an authorized representative of you regardless of who actually initiates the interaction or vocal command. You should be aware of your surroundings as vocal commands can be overheard by those nearby. You are responsible for vocal commands and other data transmitted, and products or services obtained, through the use of the Skill, including in the case of any unauthorized access by a third party. You understand that Amazon anonymizes your user ID and information communicated through Alexa, and that this means that if you contact Yno for support, Yno will not know the interactions you have had with the Skill in advance of your request for support. </p>

<p>Pilot Program. Yno is making the Skill available as an early-release pilot program to test the operation and effectiveness of the Skill. You acknowledge that the Skill is experimental and has not been fully tested and that your use of the Skill may be interrupted and/or result in errors, such as failures in voice recognition and misunderstandings of vocal commands. You agree that Yno and Amazon are not responsible for any inaccuracies that result from use of the Skill. If you are unsure about the accuracy of any information delivered by this Skill or interaction through using it, please contact Yno to confirm via the Yno website or mobile application. You understand that Yno welcomes and may seek your feedback on the Skill. All feedback provided by you shall be considered Yno intellectual property and owned by Yno. </p>

<p>Third Parties and Third Party Components. Amazon, your internet service provider, wireless carrier, and any other third parties who provide content or services that are part of, available through, or required to be used in order to use, the Skill or future enhancements are referred to in these Terms as “Third Parties.” Content and services contained in the Skill and any future enhancements provided by Third Parties are referred to as “Third Party Components.” The Third Parties are not parties to these Terms and they do not own and are not responsible for the Skill. The Third Parties are not providing any warranty for the Skill. They are not responsible for maintenance or other support services for it and shall not be responsible for any other claims, losses, liabilities, damages, costs or expenses with respect to the Skill for purposes of your Yno account(s), if you have one. Any inquiries or complaints relating to the use of the Skill, including those pertaining to intellectual property rights, must be directed to the address provided in the "Copyright Notice" link on www.Yno.com. You acknowledge and agree that the Third Parties and their subsidiaries, are third party beneficiaries of these Terms and that, upon your acceptance of these Terms , they will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary thereof. Third Party Components are provided to you under terms and conditions which are different from these Terms or which require Yno to provide you with certain notices and/or information. Yno will identify any Third Party Components and their applicable terms and conditions, if any, here. Your use of each Third Party Component will be subject to those other terms and conditions. Yno MAKES NO WARRANTIES OF ANY KIND, WHETHER EXPRESSED OR IMPLIED, WITH REGARD TO ANY THIRD-PARTY COMPONENTS. ALL THIRD-PARTY COMPONENTS ARE PROVIDED "AS-IS," WITHOUT WARRANTIES OF ANY KIND. IN NO EVENT WILL Yno BE LIABLE TO YOU OR ANY THIRD-PARTY FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE THIRD PARTY COMPONENTS, EVEN IF THEY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES. </p>

<p>DISCLAIMER OF WARRANTIES. THE SKILL IS PROVIDED ON AN "AS-AVAILABLE," "AS-IS" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, Yno AND ITS AFFILIATES, AGENTS, AND LICENSORS DISCLAIM ALL WARRANTIES WITH RESPECT TO THE SKILL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, TITLE, MERCHANTABILITY, QUIET ENJOYMENT, QUALITY OF INFORMATION, AND FITNESS FOR A PARTICULAR PURPOSE. Yno DOES NOT WARRANT THE SKILL WILL MEET YOUR REQUIREMENTS, OR THAT THE OPERATION OF THE SKILL WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE SKILL CAN OR WILL BE CORRECTED. </p>

<p>Copyrights, Trademarks, Etc. All content, trademarks (including but not limited to sound trademarks), services marks, trade names, logos, and icons are proprietary to Yno, its affiliates, agents or licensors. You may not remove any proprietary notices (e.g., copyright and trademark notices) from the Skill. Pursuant to Section 512(c)(2) of the Copyright Revision Act, as enacted through the Digital Millennium Copyright Act, Charles Yno & Co., Inc. designates an agent as described within the "Copyright Notice" link on www.Yno.com, to receive notifications of claimed infringement. </p>

<p>Privacy/Security; Wireless Limitations. Use of the Skill involves the electronic transmission of information across the networks of your internet service provider or wireless service provider. Because Yno does not operate or control the internet or wireless networks used to access the Skill, Yno is not responsible for the privacy or security of internet or wireless data transmissions. Use only reputable service providers and check with your internet or wireless service provider for information about its privacy and security practices. For additional information about privacy and security, review the "Developer Privacy Policy" link located within the Yno Skill page on the Amazon Alexa app. Wireless network coverage and Wi-Fi network speed varies by provider and geographic location. Yno is not responsible for limitations and/or failures in performance associated with any wireless or Wi-Fi service used to access the Skill or for the security of any wireless or Wi-Fi service. Wireless network coverage and Wi-Fi network speed varies by provider and geographic location. Yno is not responsible for limitations and/or failures in performance associated with any wireless or Wi-Fi service used to access the Skill or for the security of any wireless or Wi-Fi service. </p>

<p>Changes to the Skill and to these Terms. Except as otherwise required by applicable law or regulation, Yno, at any time in its sole discretion without prior notice, may (1) suspend or terminate your use and license of the Skill, (2) change the enrollment process for using the Skill, (3) update, revise, or modify the Skill, (4) reduce or suspend the types and or amounts of any transactions allowed using the Skill, and (5) discontinue support for the Skill. Yno may revise these Terms at any time, and you agree to be bound by future revisions. It is your responsibility to visit the Terms of Use link within the Yno Skill page on the Amazon Alexa app to review the most current terms and conditions. </p>

<p>General These Terms are governed by and construed in accordance with the laws of the State of California, as applied to agreements entered into and wholly performed within the State of California between California residents. Any action or proceeding brought by either party hereto shall be brought only in a state or federal court of competent jurisdiction located in San Francisco, California and the parties submit to personal jurisdiction of those courts for purposes of any action or proceeding. These Terms, including your Yno account agreement if applicable as provided above, constitute the entire understanding and agreement between you and Yno with respect to the Skill and supersedes all prior or contemporaneous oral or written communications with respect to the subject matter of these Terms, all of which are merged in these Terms. These Terms may be modified, altered or amended only as provided above. In the event any provision of these Terms is found invalid or unenforceable pursuant to judicial decree, the remainder of these Terms will remain valid and enforceable according its provisions. Any failure by Yno to strictly enforce any provision of these Terms will not operate as a waiver of that provision or any subsequent breach of that provision. The disclaimers and limitations of liability will survive any termination or expiration of these Terms. IT IS EXPRESSLY UNDERSTOOD AND AGREED THAT IN THE EVENT ANY REMEDY HEREUNDER IS DETERMINED TO HAVE FAILED OF ITS ESSENTIAL PURPOSE, ALL LIMITATIONS OF LIABILITY AND EXCLUSIONS OF DAMAGES WILL REMAIN IN EFFECT. </p>

<p>Risk Disclosure. Activities over the Internet may be subject to interruption, transmission blackout, delayed transmission due to Internet traffic or incorrect data transmission due to the public nature of the Internet. </p>

    </div>

    <div class="mobile-nav-spacer"></div>
  </div>

  <mobile-nav></mobile-nav>

`
